version: "3.7"

volumes:
  postgres-data:
  nginx-data:

services:
    nginx-website:
        image: docker.pkg.github.com/iu-2-kf-bmstu/website/frontend
        restart: always
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
            max-file: "3"
        ports: 
            - 80:80
            - 443:443
        depends_on:
          - website-api
        volumes:
            - nginx-data:/nginx-data/data/ssl/

    website-api:
        image: docker.pkg.github.com/iu-2-kf-bmstu/website/website-api
        ports: 
            - 25000:80
        restart: always
        environment:
            DbConnectionString: ${DbConnectionString}

    database:
        image: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DbUser}
            POSTGRES_PASSWORD: ${DbPassword}
        ports:
            - 25001:5432