version: "3.7"

volumes:
  postgres-data:

services:
    nginx-website:
        build:
            context: ..
            dockerfile: ./Frontend/Dockerfile
            args:
                Environment: Development
        logging:
            driver: "json-file"
            options:
                max-size: "2048m"
                max-file: "3"
        ports: 
            - 80:80
            - 443:433
        depends_on:
            - website-api
        restart: always

    website-api:
        build:
            context: ..
            dockerfile: ./Website.Api/Dockerfile
            args:
                Environment: Development
        ports: 
            - 25000:80
        restart: always
        environment:
            DbConnectionString: ${DbConnectionString}

    database:
        image: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DbUser}
            POSTGRES_PASSWORD: ${DbPassword}
        ports:
            - 5432:5432