version: "3.7"

volumes:
  postgres-data:

services:
    website-api:
        build:
            context: ..
            dockerfile: ./Website.Api/Dockerfile
            args:
                Environment: Development
        ports: 
            - 25000:80
        restart: always

    database:
        image: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432