version: "3.7"

volumes:
  postgres-data:

services:
    nginx-website:
        image: docker.pkg.github.com/iu-2-kf-bmstu/website/frontend
        restart: always
        logging:
          driver: "json-file"
          options:
            max-size: "2048m"
            max-file: "3"
        ports: 
            - "80:80"
        depends_on:
          - website-api

    website-api:
        image: docker.pkg.github.com/iu-2-kf-bmstu/website/website-api
        ports: 
            - "25000:80"
        restart: always

    database:
        image: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 64023sdfdf5964sfgd31
        ports:
            - 5432:5432