version: "3.7"

volumes:
  postgres-data:
  nginx-data:

services:
    nginx-website:
        build:
            context: ..
            dockerfile: ./Frontend/Dockerfile
        logging:
            driver: "json-file"
            options:
                max-size: "2048m"
                max-file: "3"
        ports: 
            - 80:80
            - 443:433
        depends_on:
            - website-api
        restart: always
        volumes:
            - nginx-data:/nginx-data/data/ssl/

    website-api:
        build:
            context: ..
            dockerfile: ./Website.Api/Dockerfile
            args:
                Environment: Development
        ports: 
            - 25000:80
        restart: always

    database:
        image: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432