name: Deploy

on:
  registry_package:
    
jobs:
  send-compose:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Send docker-compose file to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./docker-compose/docker-compose.deploy.yml
          remote: ./docker-compose.deploy.yml
          host: ${{ secrets.HOST_URL }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY  }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: [send-compose]
    
    steps:
      - name: SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_URL }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
             docker login docker.pkg.github.com -u 11dot001001 -p ${{ secrets.LOGIN_SECRET_GITHUB }}
             docker-compose -f docker-compose.deploy.yml pull
             docker-compose -f docker-compose.deploy.yml  up -d --force-recreate --build 