name: Frontend

on:
  push:
    branches: [ master ]

jobs:
  build-and-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Build
        run: docker build -f Frontend/Dockerfile . -t docker.pkg.github.com/iu-2-kf-bmstu/website/frontend
      - name: Login
        run: docker login docker.pkg.github.com -u 11dot001001 -p ${{ secrets.LOGIN_SECRET_GITHUB }}
      - name: Push
        run: docker push docker.pkg.github.com/iu-2-kf-bmstu/website/frontend